In [1]:
import numpy as np
import pandas as pd

In [2]:
matches_scores= pd.read_csv('./vct_2024/matches/scores.csv')

In [5]:
matches_scores

,Tournament,Stage,Match Type,Match Name,Team A,Team B,Team A Score,Team B Score,Match Result
0,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,MIBR vs Leviatán,MIBR,Leviatán,0,2,Leviatán won
1,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,Sentinels vs NRG Esports,Sentinels,NRG Esports,2,0,Sentinels won
2,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,FURIA vs 100 Thieves,FURIA,100 Thieves,2,0,FURIA won
3,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,LOUD vs Evil Geniuses,LOUD,Evil Geniuses,1,2,Evil Geniuses won
4,Champions Tour 2024: Americas Stage 2,Regular Season,Week 1,G2 Esports vs Cloud9,G2 Esports,Cloud9,2,1,G2 Esports won
...,...,...,...,...,...,...,...,...,...
395,Champions Tour 2024: Pacific Kickoff,Play-Ins,Play-ins,ZETA DIVISION vs Team Secret,ZETA DIVISION,Team Secret,0,2,Team Secret won
396,Champions Tour 2024: Pacific Kickoff,Play-Ins,Play-ins,Gen.G vs ZETA DIVISION,Gen.G,ZETA DIVISION,2,0,Gen.G won
397,Champions Tour 2024: Pacific Kickoff,Playoffs,Semifinals,T1 vs Paper Rex,T1,Paper Rex,0,2,Paper Rex won
398,Champions Tour 2024: Pacific Kickoff,Playoffs,Semifinals,DRX vs Gen.G,DRX,Gen.G,0,2,Gen.G won
399,Champions Tour 2024: Pacific Kickoff,Playoffs,Grand Final,Paper Rex vs Gen.G,Paper Rex,Gen.G,1,3,Gen.G won

In [25]:
matches_scores_AB=matches_scores[['Team A','Team B','Team A Score','Team B Score','Match Result']]

In [26]:
matches_scores_AB.columns=['Team_A','Team_B','Team_A_Score','Team_B_Score','Match_Result']

In [27]:
matches_scores_AB['Match_Result']=matches_scores_AB['Match_Result'].apply(lambda x: x.strip('won').strip())

C:\Users\PC\AppData\Local\Temp\ipykernel_2092\2020692019.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_scores_AB['Match_Result']=matches_scores_AB['Match_Result'].apply(lambda x: x.strip('won').strip())

In [28]:
matches_scores_AB.iloc[0]['Match_Result']

'Leviatán'

In [31]:
matches_scores_AB.Match_Result.value_counts()

Match_Result
Gen.G                   28
Team Heretics           21
Paper Rex               20
G2 Esports              19
EDward Gaming           17
FNATIC                  16
Sentinels               16
Leviatán                15
FunPlus Phoenix         15
Trace Esports           14
FUT Esports             13
Team Vitality           12
DRX                     12
100 Thieves             12
Karmine Corp            11
Team Secret             10
LOUD                     9
Bilibili Gaming          8
KRÜ Esports              8
T1                       8
Dragon Ranger Gaming     8
Talon Esports            8
Cloud9                   7
Natus Vincere            7
NRG Esports              6
Rex Regum Qeon           6
JDG Esports              6
Titan Esports Club       5
Team Liquid              5
Nova Esports             5
ZETA DIVISION            5
Wolves Esports           5
All Gamers               5
Evil Geniuses            5
KOI                      5
BBL Esports              4
Global Esports           4
MIBR                     4
TYLOO                    4
FURIA                    3
GIANTX                   3
Gentle Mates             3
DetonatioN FocusMe       2
BLEED                    1
Name: count, dtype: int64

In [33]:
matches_scores_AB[['Team_A','Team_B','Team_A_Score','Team_B_Score']]

            Team_A         Team_B  Team_A_Score  Team_B_Score
0             MIBR       Leviatán             0             2
1        Sentinels    NRG Esports             2             0
2            FURIA    100 Thieves             2             0
3             LOUD  Evil Geniuses             1             2
4       G2 Esports         Cloud9             2             1
..             ...            ...           ...           ...
395  ZETA DIVISION    Team Secret             0             2
396          Gen.G  ZETA DIVISION             2             0
397             T1      Paper Rex             0             2
398            DRX          Gen.G             0             2
399      Paper Rex          Gen.G             1             3

[400 rows x 4 columns]

In [34]:
df=matches_scores_AB[['Team_A','Team_B','Team_A_Score','Team_B_Score']].copy()
scores = {}

# Function to update scores
def update_scores(team, score):
    if team in scores:
        scores[team].append(score)
    else:
        scores[team] = [score]

# Update scores from the DataFrame
for _, row in df.iterrows():
    update_scores(row['Team_A'], row['Team_A_Score'])
    update_scores(row['Team_B'], row['Team_B_Score'])

# Convert the scores dictionary to a DataFrame
transposed_df = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in scores.items()]))
transposed_df.fillna(0, inplace=True)  # Optional: fill NaN values with 0

# Display the transposed DataFrame
print(transposed_df)

    MIBR  Leviatán  Sentinels  NRG Esports  FURIA  100 Thieves  LOUD  \
0    0.0       2.0        2.0          0.0    2.0          0.0   1.0
1    1.0       2.0        2.0          0.0    0.0          0.0   2.0
2    0.0       2.0        2.0          2.0    2.0          2.0   1.0
3    0.0       2.0        0.0          1.0    2.0          2.0   0.0
4    2.0       2.0        0.0          2.0    0.0          1.0   2.0
5    0.0       2.0        2.0          2.0    1.0          2.0   0.0
6    0.0       0.0        0.0          0.0    0.0          0.0   1.0
7    0.0       3.0        2.0          2.0    0.0          1.0   0.0
8    0.0       3.0        1.0          1.0    1.0          2.0   2.0
9    0.0       1.0        0.0          0.0    0.0          0.0   2.0
10   1.0       2.0        2.0          2.0    0.0          2.0   0.0
11   2.0       1.0        2.0          2.0    0.0          0.0   1.0
12   2.0       1.0        2.0          1.0    0.0          0.0   2.0
13   0.0       2.0        2.0          0.0    0.0          2.0   2.0
14   2.0       2.0        1.0          0.0    0.0          2.0   1.0
15   0.0       2.0        3.0          0.0    0.0          1.0   0.0
16   0.0       2.0        3.0          0.0    0.0          2.0   2.0
17   0.0       1.0        0.0          0.0    0.0          2.0   2.0
18   0.0       2.0        2.0          0.0    0.0          2.0   2.0
19   0.0       2.0        2.0          0.0    0.0          2.0   2.0
20   0.0       2.0        2.0          0.0    0.0          3.0   0.0
21   0.0       1.0        1.0          0.0    0.0          1.0   0.0
22   0.0       1.0        2.0          0.0    0.0          1.0   0.0
23   0.0       0.0        3.0          0.0    0.0          0.0   0.0
24   0.0       0.0        0.0          0.0    0.0          0.0   0.0
25   0.0       0.0        0.0          0.0    0.0          0.0   0.0
26   0.0       0.0        0.0          0.0    0.0          0.0   0.0
27   0.0       0.0        0.0          0.0    0.0          0.0   0.0
28   0.0       0.0        0.0          0.0    0.0          0.0   0.0
29   0.0       0.0        0.0          0.0    0.0          0.0   0.0
30   0.0       0.0        0.0          0.0    0.0          0.0   0.0
31   0.0       0.0        0.0          0.0    0.0          0.0   0.0
32   0.0       0.0        0.0          0.0    0.0          0.0   0.0
33   0.0       0.0        0.0          0.0    0.0          0.0   0.0
34   0.0       0.0        0.0          0.0    0.0          0.0   0.0
35   0.0       0.0        0.0          0.0    0.0          0.0   0.0

    Evil Geniuses  G2 Esports  Cloud9  ...  KOI  BBL Esports  FNATIC  \
0             2.0         2.0     1.0  ...  1.0          1.0     2.0
1             2.0         2.0     0.0  ...  2.0          0.0     2.0
2             0.0         2.0     2.0  ...  0.0          2.0     2.0
3             1.0         2.0     0.0  ...  2.0          1.0     2.0
4             0.0         2.0     1.0  ...  1.0          0.0     2.0
5             0.0         2.0     2.0  ...  0.0          2.0     2.0
6             1.0         1.0     2.0  ...  0.0          2.0     2.0
7             0.0         2.0     2.0  ...  0.0          2.0     3.0
8             2.0         2.0     0.0  ...  1.0          0.0     1.0
9             2.0         2.0     2.0  ...  2.0          0.0     1.0
10            2.0         2.0     2.0  ...  0.0          1.0     0.0
11            1.0         0.0     0.0  ...  2.0          0.0     2.0
12            0.0         0.0     2.0  ...  2.0          0.0     2.0
13            0.0         2.0     0.0  ...  0.0          0.0     2.0
14            0.0         0.0     0.0  ...  0.0          0.0     0.0
15            0.0         2.0     0.0  ...  0.0          0.0     1.0
16            0.0         1.0     0.0  ...  0.0          0.0     2.0
17            0.0         2.0     0.0  ...  0.0          0.0     2.0
18            0.0         0.0     0.0  ...  0.0          0.0     0.0
19            0.0         2.0     0.0  ...  0.0          0.0     3.0
20            0.0         2.0     0.0  ...  0.0          0.0     3.0
21            0.0         1.0     0.0  ...  0.0          0.0     2.0
22            0.0         3.0     0.0  ...  0.0          0.0     0.0
23            0.0         0.0     0.0  ...  0.0          0.0     0.0
24            0.0         2.0     0.0  ...  0.0          0.0     0.0
25            0.0         0.0     0.0  ...  0.0          0.0     0.0
26            0.0         2.0     0.0  ...  0.0          0.0     0.0
27            0.0         1.0     0.0  ...  0.0          0.0     0.0
28            0.0         2.0     0.0  ...  0.0          0.0     0.0
29            0.0         0.0     0.0  ...  0.0          0.0     0.0
30            0.0         0.0     0.0  ...  0.0          0.0     0.0
31            0.0         0.0     0.0  ...  0.0          0.0     0.0
32            0.0         0.0     0.0  ...  0.0          0.0     0.0
33            0.0         0.0     0.0  ...  0.0          0.0     0.0
34            0.0         0.0     0.0  ...  0.0          0.0     0.0
35            0.0         0.0     0.0  ...  0.0          0.0     0.0

    Team Heretics  Natus Vincere  GIANTX  Gentle Mates  Team Vitality  \
0             2.0            0.0     2.0           1.0            2.0
1             2.0            0.0     0.0           2.0            1.0
2             2.0            0.0     2.0           0.0            2.0
3             2.0            0.0     1.0           1.0            2.0
4             2.0            2.0     0.0           1.0            2.0
5             1.0            1.0     0.0           2.0            2.0
6             2.0            2.0     1.0           0.0            0.0
7             1.0            2.0     1.0           0.0            3.0
8             2.0            2.0     1.0           2.0            1.0
9             1.0            1.0     2.0           0.0            0.0
10            2.0            2.0     1.0           0.0            2.0
11            2.0            0.0     1.0           1.0            2.0
12            1.0            2.0     0.0           0.0            0.0
13            2.0            2.0     0.0           0.0            2.0
14            2.0            0.0     0.0           0.0            1.0
15            3.0            0.0     0.0           0.0            2.0
16            2.0            0.0     0.0           0.0            0.0
17            2.0            0.0     0.0           0.0            2.0
18            1.0            0.0     0.0           0.0            0.0
19            0.0            0.0     0.0           0.0            2.0
20            2.0            0.0     0.0           0.0            0.0
21            2.0            0.0     0.0           0.0            0.0
22            2.0            0.0     0.0           0.0            0.0
23            2.0            0.0     0.0           0.0            0.0
24            2.0            0.0     0.0           0.0            0.0
25            2.0            0.0     0.0           0.0            0.0
26            1.0            0.0     0.0           0.0            0.0
27            1.0            0.0     0.0           0.0            0.0
28            2.0            0.0     0.0           0.0            0.0
29            2.0            0.0     0.0           0.0            0.0
30            2.0            0.0     0.0           0.0            0.0
31            1.0            0.0     0.0           0.0            0.0
32            0.0            0.0     0.0           0.0            0.0
33            0.0            0.0     0.0           0.0            0.0
34            0.0            0.0     0.0           0.0            0.0
35            0.0            0.0     0.0           0.0            0.0

    Team Liquid  Karmine Corp
0           0.0           2.0
1           0.0           0.0
2           2.0           0.0
3           0.0           1.0
4           2.0           1.0
5           0.0           2.0
6           1.0           1.0
7           2.0           2.0
8           0.0           1.0
9           2.0           2.0
10          1.0           1.0
11          2.0           0.0
12          0.0           0.0
13          1.0           2.0
14          0.0           0.0
15          0.0           1.0
16          0.0           2.0
17          0.0           0.0
18          0.0           2.0
19          0.0           2.0
20          0.0           2.0
21          0.0           2.0
22          0.0           3.0
23          0.0           0.0
24          0.0           0.0
25          0.0           0.0
26          0.0           0.0
27          0.0           0.0
28          0.0           0.0
29          0.0           0.0
30          0.0           0.0
31          0.0           0.0
32          0.0           0.0
33          0.0           0.0
34          0.0           0.0
35          0.0           0.0

[36 rows x 44 columns]

In [37]:
transposed_df.mean().sort_values(ascending=False)

Gen.G                   1.944444
Team Heretics           1.527778
Paper Rex               1.333333
G2 Esports              1.194444
EDward Gaming           1.138889
Leviatán                1.111111
FunPlus Phoenix         1.083333
Sentinels               1.055556
FNATIC                  1.055556
Trace Esports           0.916667
DRX                     0.833333
100 Thieves             0.833333
FUT Esports             0.833333
Karmine Corp            0.805556
Team Vitality           0.777778
LOUD                    0.694444
Team Secret             0.638889
KRÜ Esports             0.638889
Bilibili Gaming         0.583333
T1                      0.583333
Dragon Ranger Gaming    0.555556
Talon Esports           0.527778
Natus Vincere           0.444444
Rex Regum Qeon          0.444444
ZETA DIVISION           0.444444
JDG Esports             0.444444
Cloud9                  0.444444
Titan Esports Club      0.416667
NRG Esports             0.416667
KOI                     0.361111
Team Liquid             0.361111
Nova Esports            0.361111
Evil Geniuses           0.361111
Wolves Esports          0.333333
GIANTX                  0.333333
TYLOO                   0.305556
All Gamers              0.305556
Global Esports          0.305556
BBL Esports             0.305556
Gentle Mates            0.277778
MIBR                    0.277778
FURIA                   0.222222
DetonatioN FocusMe      0.222222
BLEED                   0.222222
dtype: float64

In [42]:
teams_qualified = [
    "DRX",
    "Gen.G",
    "Paper Rex",
    "Talon Esports",
    "EDward Gaming",
    "FunPlus Phoenix",
    "Trace Esports",
    "Bilibili Gaming",
    "FNATIC",
    "FUT Esports",
    "Team Heretics",
    "Team Vitality",
    "Leviatán",
    "Sentinels",
    "G2 Esports",
    "KRÜ Esports"
]

In [43]:
transposed_df.columns

Index(['MIBR', 'Leviatán', 'Sentinels', 'NRG Esports', 'FURIA', '100 Thieves',
       'LOUD', 'Evil Geniuses', 'G2 Esports', 'Cloud9', 'KRÜ Esports',
       'Titan Esports Club', 'JDG Esports', 'All Gamers', 'TYLOO',
       'Bilibili Gaming', 'Wolves Esports', 'Dragon Ranger Gaming',
       'Nova Esports', 'FunPlus Phoenix', 'Trace Esports', 'EDward Gaming',
       'ZETA DIVISION', 'DRX', 'Team Secret', 'BLEED', 'T1', 'Gen.G',
       'Paper Rex', 'Talon Esports', 'Rex Regum Qeon', 'DetonatioN FocusMe',
       'Global Esports', 'FUT Esports', 'KOI', 'BBL Esports', 'FNATIC',
       'Team Heretics', 'Natus Vincere', 'GIANTX', 'Gentle Mates',
       'Team Vitality', 'Team Liquid', 'Karmine Corp'],
      dtype='object')

In [71]:
filtered_df = transposed_df.loc[:, transposed_df.columns.isin(teams_qualified)]

In [72]:
filtered_df.head()

,Leviatán,Sentinels,G2 Esports,KRÜ Esports,Bilibili Gaming,FunPlus Phoenix,Trace Esports,EDward Gaming,DRX,Gen.G,Paper Rex,Talon Esports,FUT Esports,FNATIC,Team Heretics,Team Vitality
0,2.0,2.0,2.0,0.0,2.0,1.0,2.0,1.0,2.0,2,2.0,0.0,2.0,2.0,2.0,2.0
1,2.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,1.0,2,2.0,2.0,2.0,2.0,2.0,1.0
2,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,0.0,2,2.0,2.0,0.0,2.0,2.0,2.0
3,2.0,0.0,2.0,2.0,0.0,0.0,2.0,2.0,2.0,1,2.0,1.0,2.0,2.0,2.0,2.0
4,2.0,0.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2,2.0,1.0,2.0,2.0,2.0,2.0

In [74]:
filtered_df1= filtered_df.mean().reset_index()

In [59]:
matches_res = matches_scores_AB.Match_Result.value_counts()

In [66]:
filtered_df2 = matches_res[matches_res.index.isin(teams_qualified)].reset_index()

In [77]:
filtered_df1.columns=['team','mean_win']

In [76]:
filtered_df2.columns=['team','count_win']

In [78]:
matches_win=filtered_df1.merge(filtered_df2,on='team')

In [79]:
matches_win

               team  mean_win  count_win
0          Leviatán  1.111111         15
1         Sentinels  1.055556         16
2        G2 Esports  1.194444         19
3       KRÜ Esports  0.638889          8
4   Bilibili Gaming  0.583333          8
5   FunPlus Phoenix  1.083333         15
6     Trace Esports  0.916667         14
7     EDward Gaming  1.138889         17
8               DRX  0.833333         12
9             Gen.G  1.944444         28
10        Paper Rex  1.333333         20
11    Talon Esports  0.527778          8
12      FUT Esports  0.833333         13
13           FNATIC  1.055556         16
14    Team Heretics  1.527778         21
15    Team Vitality  0.777778         12

In [103]:
matches_win.to_csv('./data/matches_win_16.csv',index=False)

In [80]:
players=pd.read_csv('vct_2024/players_stats/players_stats.csv')

In [82]:
players.columns

Index(['Tournament', 'Stage', 'Match Type', 'Player', 'Teams', 'Agents',
       'Rounds Played', 'Rating', 'Average Combat Score', 'Kills:Deaths',
       'Kill, Assist, Trade, Survive %', 'Average Damage Per Round',
       'Kills Per Round', 'Assists Per Round', 'First Kills Per Round',
       'First Deaths Per Round', 'Headshot %', 'Clutch Success %',
       'Clutches (won/played)', 'Maximum Kills in a Single Map', 'Kills',
       'Deaths', 'Assists', 'First Kills', 'First Deaths'],
      dtype='object')

In [83]:
players.dtypes

Tournament                         object
Stage                              object
Match Type                         object
Player                             object
Teams                              object
Agents                             object
Rounds Played                       int64
Rating                            float64
Average Combat Score                int64
Kills:Deaths                      float64
Kill, Assist, Trade, Survive %     object
Average Damage Per Round          float64
Kills Per Round                   float64
Assists Per Round                 float64
First Kills Per Round             float64
First Deaths Per Round            float64
Headshot %                         object
Clutch Success %                   object
Clutches (won/played)              object
Maximum Kills in a Single Map       int64
Kills                               int64
Deaths                              int64
Assists                             int64
First Kills                         int64
First Deaths                        int64
dtype: object

In [84]:
players.iloc[0]

Tournament                        Champions Tour 2024: Masters Madrid
Stage                                                        Playoffs
Match Type                                           Upper Semifinals
Player                                                       cauanzin
Teams                                                            LOUD
Agents                                                         breach
Rounds Played                                                      43
Rating                                                           1.06
Average Combat Score                                              253
Kills:Deaths                                                     1.06
Kill, Assist, Trade, Survive %                                    70%
Average Damage Per Round                                        155.0
Kills Per Round                                                  0.81
Assists Per Round                                                0.28
First Kills Per Round                                            0.02
First Deaths Per Round                                           0.12
Headshot %                                                        25%
Clutch Success %                                                  NaN
Clutches (won/played)                                             0/2
Maximum Kills in a Single Map                                      18
Kills                                                              35
Deaths                                                             33
Assists                                                            12
First Kills                                                         1
First Deaths                                                        5
Name: 0, dtype: object

In [85]:
player_data=['Player','Teams','Rounds Played', 'Rating', 'Average Combat Score', 'Kills:Deaths',
       'Kill, Assist, Trade, Survive %', 'Average Damage Per Round',
       'Kills Per Round', 'Assists Per Round', 'First Kills Per Round',
       'First Deaths Per Round','Maximum Kills in a Single Map', 'Kills',
       'Deaths', 'Assists', 'First Kills', 'First Deaths']

In [88]:
players_df=players[player_data]

In [90]:
players_df.Teams.unique()

array(['LOUD', 'Sentinels', 'Paper Rex', 'Gen.G', 'Team Heretics',
       'EDward Gaming', 'FunPlus Phoenix', 'Karmine Corp', 'G2 Esports',
       '100 Thieves', 'FNATIC', 'FUT Esports', 'T1',
       'Dragon Ranger Gaming', 'Leviatán', 'Trace Esports', 'All Gamers',
       'Bilibili Gaming', 'JDG Esports', 'Wolves Esports',
       'Titan Esports Club', 'TYLOO', 'Nova Esports', 'Rex Regum Qeon',
       'Talon Esports', 'Team Secret', 'DRX', 'ZETA DIVISION',
       'Global Esports', 'BLEED', 'DetonatioN FocusMe', 'KRÜ Esports',
       'Cloud9', 'FURIA', 'NRG Esports', 'Evil Geniuses', 'MIBR',
       'Team Vitality', 'Natus Vincere', 'Gentle Mates', 'GIANTX',
       'BBL Esports', 'KOI', 'Team Liquid'], dtype=object)

In [94]:
players_df=players_df[players_df.Teams.isin(teams_qualified)]

In [96]:
len(players_df.Teams.unique())

16

In [97]:
players_df

,Player,Teams,Rounds Played,Rating,Average Combat Score,Kills:Deaths,"Kill, Assist, Trade, Survive %",Average Damage Per Round,Kills Per Round,Assists Per Round,First Kills Per Round,First Deaths Per Round,Maximum Kills in a Single Map,Kills,Deaths,Assists,First Kills,First Deaths
15,johnqt,Sentinels,43,1.13,232,1.24,79%,152.0,0.84,0.21,0.16,0.05,21,36,29,9,7,2
16,johnqt,Sentinels,26,1.18,231,1.31,73%,160.0,0.81,0.23,0.04,0.04,21,21,16,6,1,1
17,johnqt,Sentinels,69,1.14,232,1.27,77%,155.0,0.83,0.22,0.12,0.04,21,57,45,15,8,3
18,Sacy,Sentinels,52,0.73,151,0.69,54%,106.0,0.52,0.13,0.02,0.17,18,27,39,7,1,9
19,Sacy,Sentinels,17,0.94,178,0.83,88%,108.0,0.59,0.47,0.24,0.00,10,10,12,8,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13670,Leo,FNATIC,88,1.05,187,1.13,77%,126.0,0.67,0.33,0.07,0.05,24,59,52,29,6,4
13671,Derke,FNATIC,18,1.13,255,1.31,72%,160.0,0.94,0.11,0.28,0.22,17,17,13,2,5,4
13672,Derke,FNATIC,70,0.73,166,0.73,60%,108.0,0.57,0.07,0.17,0.19,15,40,55,5,12,13
13673,Derke,FNATIC,88,0.83,188,0.84,63%,119.0,0.65,0.08,0.19,0.19,17,57,68,7,17,17
13674,Boaster,FNATIC,88,1.01,200,1.03,70%,135.0,0.73,0.43,0.07,0.10,20,64,62,38,6,9

In [100]:
players_df['Kill, Assist, Trade, Survive %']=players_df['Kill, Assist, Trade, Survive %'].str.strip('%').astype(float)

C:\Users\PC\AppData\Local\Temp\ipykernel_2092\3891290767.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_df['Kill, Assist, Trade, Survive %']=players_df['Kill, Assist, Trade, Survive %'].str.strip('%').astype(float)

In [105]:
players_df.dtypes

Player                             object
Teams                              object
Rounds Played                       int64
Rating                            float64
Average Combat Score                int64
Kills:Deaths                      float64
Kill, Assist, Trade, Survive %    float64
Average Damage Per Round          float64
Kills Per Round                   float64
Assists Per Round                 float64
First Kills Per Round             float64
First Deaths Per Round            float64
Maximum Kills in a Single Map       int64
Kills                               int64
Deaths                              int64
Assists                             int64
First Kills                         int64
First Deaths                        int64
dtype: object

In [101]:
players_df

,Player,Teams,Rounds Played,Rating,Average Combat Score,Kills:Deaths,"Kill, Assist, Trade, Survive %",Average Damage Per Round,Kills Per Round,Assists Per Round,First Kills Per Round,First Deaths Per Round,Maximum Kills in a Single Map,Kills,Deaths,Assists,First Kills,First Deaths
15,johnqt,Sentinels,43,1.13,232,1.24,79.0,152.0,0.84,0.21,0.16,0.05,21,36,29,9,7,2
16,johnqt,Sentinels,26,1.18,231,1.31,73.0,160.0,0.81,0.23,0.04,0.04,21,21,16,6,1,1
17,johnqt,Sentinels,69,1.14,232,1.27,77.0,155.0,0.83,0.22,0.12,0.04,21,57,45,15,8,3
18,Sacy,Sentinels,52,0.73,151,0.69,54.0,106.0,0.52,0.13,0.02,0.17,18,27,39,7,1,9
19,Sacy,Sentinels,17,0.94,178,0.83,88.0,108.0,0.59,0.47,0.24,0.00,10,10,12,8,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13670,Leo,FNATIC,88,1.05,187,1.13,77.0,126.0,0.67,0.33,0.07,0.05,24,59,52,29,6,4
13671,Derke,FNATIC,18,1.13,255,1.31,72.0,160.0,0.94,0.11,0.28,0.22,17,17,13,2,5,4
13672,Derke,FNATIC,70,0.73,166,0.73,60.0,108.0,0.57,0.07,0.17,0.19,15,40,55,5,12,13
13673,Derke,FNATIC,88,0.83,188,0.84,63.0,119.0,0.65,0.08,0.19,0.19,17,57,68,7,17,17
13674,Boaster,FNATIC,88,1.01,200,1.03,70.0,135.0,0.73,0.43,0.07,0.10,20,64,62,38,6,9

In [102]:
players_df.to_csv('./data/players_stats.csv',index=False)

In [104]:
players_df.columns

Index(['Player', 'Teams', 'Rounds Played', 'Rating', 'Average Combat Score',
       'Kills:Deaths', 'Kill, Assist, Trade, Survive %',
       'Average Damage Per Round', 'Kills Per Round', 'Assists Per Round',
       'First Kills Per Round', 'First Deaths Per Round',
       'Maximum Kills in a Single Map', 'Kills', 'Deaths', 'Assists',
       'First Kills', 'First Deaths'],
      dtype='object')

In [106]:
agg_dict={'Rounds Played':'sum', 'Rating':'mean', 'Average Combat Score':'mean',
       'Kills:Deaths':'mean', 'Kill, Assist, Trade, Survive %':'mean',
       'Average Damage Per Round':'mean', 'Kills Per Round':'sum', 'Assists Per Round':'sum',
       'First Kills Per Round':'sum', 'First Deaths Per Round':'sum',
       'Maximum Kills in a Single Map':'sum', 'Kills':'sum', 'Deaths':'sum', 'Assists':'sum',
       'First Kills':'sum', 'First Deaths':'sum'}

In [109]:
teams_st=players_df.groupby('Teams',as_index=False).agg(agg_dict)

In [110]:
teams_st

,Teams,Rounds Played,Rating,Average Combat Score,Kills:Deaths,"Kill, Assist, Trade, Survive %",Average Damage Per Round,Kills Per Round,Assists Per Round,First Kills Per Round,First Deaths Per Round,Maximum Kills in a Single Map,Kills,Deaths,Assists,First Kills,First Deaths
0,Bilibili Gaming,17091,NaN,198.343234,1.022046,NaN,133.553846,209.04,100.49,13.07,12.22,5127,11889,11820,5664,742,707
1,DRX,21104,1.040665,199.196203,1.087405,73.272152,130.572785,222.29,92.25,30.52,30.66,5531,14683,14444,6160,2055,2145
2,EDward Gaming,26597,0.909531,200.189130,1.075370,67.843750,129.600858,328.24,134.96,22.02,24.14,7985,19233,18333,7830,1159,1243
3,FNATIC,25255,1.062781,203.754630,1.149468,73.513369,134.576389,309.06,134.54,43.59,43.41,7516,18068,16484,7831,2549,2494
4,FUT Esports,23796,1.056146,199.765854,1.063317,73.053156,130.890244,288.38,129.76,40.03,42.13,7104,16734,16380,7526,2322,2452
5,FunPlus Phoenix,29922,0.878649,206.132911,1.084346,65.243243,133.891129,345.02,131.11,26.48,24.08,8721,21364,20803,8232,1764,1676
6,G2 Esports,30443,1.015185,195.686957,1.015587,72.492877,128.619565,315.41,145.03,44.39,47.27,7914,21057,21284,9267,2982,3115
7,Gen.G,43541,1.037979,202.121739,1.104800,73.008511,133.297391,412.31,172.30,59.64,53.05,10518,31225,29149,13119,4568,4116
8,KRÜ Esports,19651,0.988067,192.886667,1.015733,70.556667,129.503333,203.79,81.39,30.22,30.37,5097,13641,13658,5396,1968,1972
9,Leviatán,26781,1.067755,206.323529,1.152010,74.586006,136.316176,298.50,122.50,43.03,39.23,7582,19660,17748,8025,2862,2505
10,Paper Rex,32313,1.066536,204.681736,1.107107,74.206186,134.587703,401.62,177.70,56.90,52.40,9563,23461,22173,10153,3350,3133
11,Sentinels,25969,1.049362,198.882979,1.064628,74.090426,130.287234,259.17,129.73,36.68,35.56,6540,18294,17270,8876,2693,2453
12,Talon Esports,16527,0.946424,189.582278,0.969557,68.984177,125.607595,210.04,78.24,30.36,33.95,5132,11020,11633,4115,1615,1717
13,Team Heretics,34821,1.053627,202.760512,1.129488,73.811083,133.848263,393.68,177.65,58.84,50.57,9740,24702,23641,11145,3714,3251
14,Team Vitality,22251,0.994636,195.714286,1.014431,70.661808,128.924198,234.78,107.44,33.84,34.69,5929,15324,15483,7138,2146,2295
15,Trace Esports,23365,NaN,200.614035,1.044006,NaN,125.470588,241.66,102.36,11.76,11.83,6053,16629,16286,7050,960,925

In [111]:
teams_st.to_csv('./data/teams_stats.csv',index=False)